# Generated by Django 5.2 on 2025-04-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
